export const SQL_CONNECTION = 'SQL_CONNECTION';
export const MONGO_CONNECTION = 'MONGO_CONNECTION';

export const REFRESH_TOKEN_REPOSITORY = 'REFRESH_TOKEN_REPOSITORY';
export const FOLLOWER_REPOSITORY = 'FOLLOWER_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
