export const SQL_CONNECTION_TOKEN = 'SqlConnectionToken';
export const MONGO_CONNECTION_TOKEN = 'MongoConnectionToken';

export const REFRESH_TOKEN_REPOSITORY = 'REFRESH_TOKEN_REPOSITORY';
export const POST_SCHEMA_REPOSITORY = 'POST_SCHEMA_REPOSITORY';

export const USER_REPOSITORY = 'USER_REPOSITORY';
